### ISSUE TITLE
I'm getting 500 for a 'cuadrante'

### ISSUE THREAD

**Issue by razeone** [diegovalle/hoyodecrimen.api#33]
If I don't share my current location it takes the following cuadrante `KeyError: u'C-1.4.4'`, which actually produces an error.

**Comment by razeone** [comment]
Same error in tests.

**Comment by diegovalle** [comment]
All the tests are passing in travis-ci. If you are getting a key error for cuadrante C-1.4.4 you are using an old polygon file. Could you delete the cuadrantes_poly table and update it with the latest version 

```sh
psql -d apihoyodecrimen < data/cuadrantes_poly.sql
```

**Comment by razeone** [comment]
Then the shapefile needs to be update right? Since I generated the `cuadrantes_poly.sql` from it.

**Comment by diegovalle** [comment]
Yes, it's no longer in master

**Comment by razeone** [comment]
Good!
