### ISSUE TITLE
Not getting points for `cuadrante`

### ISSUE THREAD

**Issue by razeone** [diegovalle/hoyodecrimen.api#34]
So I have all running in local but I'm getting the home map as follows:

<img width="1215" alt="captura de pantalla 2016-11-11 a la s 19 49 21" src="https://cloud.githubusercontent.com/assets/825748/20234887/710589b2-a849-11e6-8db5-135028b6e753.png">

I see that productive version loads a single file for `pip_req.js` and the repo version loads several different JS files. I'm trying to figure out the reason, but not yet. Do you have any ide of where should I look?

**Comment by diegovalle** [comment]
The js file are combined and minified in the development version, if you want this to happen during development you have to change ```app.config['ASSETS_DEBUG'] = True``` to False in https://github.com/diegovalle/hoyodecrimen.api/blob/master/wsgi/hoyodecrimen.py#L451

**Comment by diegovalle** [comment]
If you connect to the apihoyodecrimen database and run 

```sql
SELECT upper(crime_latlong.crime) AS crime, upper(crime_latlong.date) AS date, upper(crime_latlong.hour) AS hour, crime_latlong.latitude AS lat, crime_latlong.longitude AS long 
FROM crime_latlong 
WHERE ST_DWithin(CAST(crime_latlong.geom AS geography(GEOMETRY,-1)), ST_GeomFromText('POINT(-99.13890838623047 19.43195295046888)', 4326), 500)  ORDER BY crime_latlong.crime DESC, crime_latlong.date DESC;
```

what's the output?

**Comment by razeone** [comment]
Empty

**Comment by diegovalle** [comment]
And when you run

```sql
SELECT upper(crime_latlong.crime) AS crime, upper(crime_latlong.date) AS date, upper(crime_latlong.hour) AS hour, crime_latlong.latitude AS lat, crime_latlong.longitude AS long 
FROM crime_latlong LIMIT 10;
```

**Comment by razeone** [comment]
```
"VIOLACION";"2013-01-01";"10:07";19.5440795241155;-99.1247208081161
"ROBO A NEGOCIO C.V.";"2013-01-01";"18:36";19.1883590004325;-99.0744830000001
"ROBO DE VEHICULO AUTOMOTOR S.V.";"2013-01-01";"01:31";19.3808172593185;-99.199885457738
"ROBO A TRANSEUNTE C.V.";"2013-01-01";"14:54";19.3695046814212;-99.1998346745779
"ROBO DE VEHICULO AUTOMOTOR S.V.";"2013-01-01";"18:31";19.3933594899586;-99.1994512081143
"LESIONES POR ARMA DE FUEGO";"2013-01-01";"20:03";19.38711527288;-99.2217777371028
"ROBO A TRANSEUNTE C.V.";"2013-01-01";"20:35";19.5068167104704;-99.2010551691058
"ROBO A TRANSEUNTE C.V.";"2013-01-01";"23:11";19.4998596459772;-99.1911748051919
"ROBO A TRANSEUNTE C.V.";"2013-01-01";"10:11";19.4680261030373;-99.184175692499
"LESIONES POR ARMA DE FUEGO";"2013-01-01";"07:41";;
```

**Comment by diegovalle** [comment]
Looks like the latitude and longitude are not geoms. Can you run the index.sql file in the ansible/roles/hoyodecrimen.app/files/ directory

**Comment by razeone** [comment]
Cool, It works now! Thanks Diego!
